# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'barterApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'SwiftyOnboard'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'
  pod 'Kingfisher'
  pod 'Hero'
  pod 'EFImageViewZoom', :git => 'https://github.com/ezefranca/EFImageViewZoom.git'
  pod 'SwiftEntryKit'



  # Pods for barterApp

  target 'barterAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'barterAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
